version: '3.9'
networks:
  gateway_network:
    driver: bridge

services:
  gatewayservice:
    build: ./src/Gateway
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      - authservice
      - userservice
      - projectservice
      - rabbitmq
    networks:
      - gateway_network

  authservice:
    build:
      context: .
      dockerfile: ./src/Services/AuthService/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=authdb;Database=auth_db;Username=postgres;Password=postgres;
    depends_on:
      - authdb
      - rabbitmq
    container_name: authservice
    networks:
      - gateway_network

  userservice:
    build:
      context: .
      dockerfile: ./src/Services/UserService/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=userdb;Database=user_db;Username=postgres;Password=postgres;
    depends_on:
      - userdb
      - rabbitmq
    container_name: userservice
    networks:
      - gateway_network

  projectservice:
    build:
      context: .
      dockerfile: ./src/Services/ProjectService/Dockerfile
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=projectdb;Database=project_db;Username=postgres;Password=postgres;
    depends_on:
      - projectdb
      - rabbitmq
    container_name: projectservice
    networks:
      - gateway_network

  authdb:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "auth_db"
    ports:
      - "5433:5432"
    networks:
      - gateway_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  userdb:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "user_db"
    ports:
      - "5434:5432"
    networks:
      - gateway_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  projectdb:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "project_db"
    ports:
      - "5435:5432"
    networks:
      - gateway_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gateway_network
