version: '3.9'
networks:
  gateway_network:
    driver: bridge

services:
  gatewayservice:
    build: ./src/GatewayService
    ports:
      - "5010:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - authservice
      - userservice
      - projectservice
      - rabbitmq
    networks:
      - gateway_network

  authservice:
    build:
      context: .
      dockerfile: ./src/AuthService/Dockerfile
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=authdb;Database=auth_db;Username=postgres;Password=postgres;"
    depends_on:
      - authdb
      - rabbitmq
    networks:
      - gateway_network

  userservice:
    build:
      context: .
      dockerfile: ./src/UserService/Dockerfile
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=userdb;Database=user_db;Username=postgres;Password=postgres;"
    depends_on:
      - userdb
      - rabbitmq
    networks:
      - gateway_network

  projectservice:
    build:
      context: .
      dockerfile: ./src/ProjectService/Dockerfile
    ports:
      - "5003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Host=projectdb;Database=project_db;Username=postgres;Password=postgres;"
    depends_on:
      - projectdb
      - rabbitmq
    networks:
      - gateway_network

  authdb:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "auth_db"
    ports:
      - "5433:5432"
    networks:
      - gateway_network

  userdb:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "user_db"
    networks:
      - gateway_network

  projectdb:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "project_db"
    networks:
      - gateway_network

  # MongoDB для сервисов, которые используют NoSQL
  # mongodb:
  #   image: mongo:5
  #   ports:
  #     - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gateway_network
