name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Restore dependencies
        run: dotnet restore MicroservicesMonorepo.sln

      - name: Build backend
        run: dotnet build MicroservicesMonorepo.sln --no-restore -c Release

      - name: Test backend
        run: dotnet test MicroservicesMonorepo.sln --no-build -c Release

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
