name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий вместе с submodule
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive # Инициализируем и обновляем submodules

      # Шаг 2: Настраиваем .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Шаг 3: Настраиваем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Шаг 4: Восстанавливаем зависимости для backend
      - name: Restore backend dependencies
        run: dotnet restore MicroservicesMonorepo.sln

      # Шаг 5: Сборка backend
      - name: Build backend
        run: dotnet build MicroservicesMonorepo.sln --no-restore -c Release

      # Шаг 6: Тестирование backend
      - name: Test backend
        run: dotnet test MicroservicesMonorepo.sln --no-build -c Release

      # Шаг 7: Устанавливаем зависимости для frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install --legacy-peer-deps

      # Шаг 8: Сборка frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
